### ISSUE TITLE
What about documentation?

### ISSUE THREAD

**Issue by UliPrantz** [spebbe/dartz#72] opened 2021-01-12 22:30 UTC
I think it would help many people and also would make this package more accepted and useful when there would be any documentation. Things like explaining what functions of Either or Option do would be really helpful (even if it's just copied from some documentation of another functional language). Didn't look into other classes yet but I assume the documentation is missing on all of them.

**Comment by mateusfccp** [comment] 2021-01-13 11:21
This is a duplicate of #36.

I am working on documentation, but I don't have much spare time. You can help with the issue if you feel like it, your help would be welcome.

**Comment by spebbe** [comment] 2021-01-15 07:55
Duplicate of #36

**Closed by spebbe** 2021-01-15 07:55 UTC
